const fs=require('fs'),vm=require('vm'),assert=require('assert');
class E{constructor(tag){this.tag=tag;this.style={};this.dataset={};this.children=[];}append(e){this.children.push(e);e.parentElement=this;}setAttribute(){}replaceChildren(...items){this.children=[];items.forEach(e=>this.append(e));}querySelector(tag){return this.children.find(x=>x.tag===tag);}get lastElementChild(){return this.children.at(-1);}focus(){}scrollIntoView(){}showModal(){}close(){}remove(){}addEventListener(k,f){this[k]=f;}}
let ext,handlers={},timers=[],body=new E('body');const app={graph:{setDirtyCanvas(){},getNodeById(){return {}; }},registerExtension(e){ext=e;}};const api={addEventListener(k,f){handlers[k]=f;},queuePrompt:async()=>({})};let ctx={app,api,document:{createElement:t=>new E(t),body},crypto:require('crypto').webcrypto,Map,Date,setTimeout:f=>{timers.push(f);return f;},clearTimeout(){},setInterval:f=>f,clearInterval(){},queueMicrotask:f=>f()};vm.createContext(ctx);
const root=process.argv[2];function run(f){vm.runInContext(fs.readFileSync(root+f,'utf8').replace(/^import .*;\n/gm,'').replace(/export function /g,'function '),ctx);}
run('dialogue_blocks.js');let original=JSON.stringify({blocks:[{id:'a',text:'元の台詞。'}]});let w={name:'dialogue_blocks',value:original},node={id:1,comfyClass:'LocalNarrationDirection',widgets:[w,{name:'text',value:'旧原稿'},{name:'mode',value:'手動'}],addWidget(t,n,v,fn){this.open=fn;return {};}};ext.nodeCreated(node);const find=(e,t)=>e.children.flatMap(x=>[x,...find(x,t)]).filter(x=>x.tag===t);node.open();let dialog=body.children.at(-1);let text=find(dialog,'textarea')[0];text.value='変更。';text.oninput();assert.equal(w.value,original);find(dialog,'button').find(x=>x.textContent.startsWith('Cancel')).onclick();assert.equal(w.value,original);node.open();dialog=body.children.at(-1);assert.equal(find(dialog,'textarea')[0].value,'元の台詞。');text=find(dialog,'textarea')[0];text.value='保存する台詞。';text.oninput();find(dialog,'button').find(x=>x.textContent.startsWith('Save')).onclick();assert.equal(JSON.parse(w.value).blocks[0].text,'保存する台詞。');node.open();dialog=body.children.at(-1);text=find(dialog,'textarea')[0];text.value='破棄';text.oninput();dialog.cancel({preventDefault(){}});assert.equal(JSON.parse(w.value).blocks[0].text,'保存する台詞。');
run('status.js');handlers['local_narration.status']({detail:{node:1,state:'running',text:'LM Studio読み込み'}});let panel=body.children.at(-1);assert(panel.textContent.includes('経過'));assert.equal(panel.dataset.state,'running');handlers['local_narration.status']({detail:{node:1,state:'complete',text:'1文終了'}});assert.equal(panel.dataset.state,'running');handlers.executed({detail:{output:{completed_audio:[{}]}}});assert.equal(panel.dataset.state,'complete');handlers['local_narration.status']({detail:{node:1,state:'running',text:'再実行'}});handlers.reconnecting();assert.equal(panel.dataset.state,'error');assert(panel.textContent.includes('未確認'));console.log('PASS: draft cancel, Escape cancel, save, progress, per-sentence non-completion, final completion, disconnect');

const modal=new E('dialog');
handlers['local_narration.consult_status']({detail:{state:'running',text:'AIに相談中',dialog:modal}});
assert.equal(panel.parentElement,body,'progress remains visible after consultation modal closes');assert(panel.textContent.includes('AIに相談中'));assert(panel.textContent.includes('経過'));
handlers.execution_success();assert.equal(panel.dataset.state,'running','Unrelated queue completion must not finish consultation');
handlers['local_narration.consult_status']({detail:{state:'complete',text:'提案完了',dialog:modal}});
assert.equal(panel.dataset.state,'complete');
handlers['local_narration.consult_status']({detail:{state:'detach',dialog:modal}});assert.equal(panel.parentElement,body);
handlers['local_narration.consult_status']({detail:{state:'running',text:'相談中',dialog:modal}});
handlers['local_narration.consult_status']({detail:{state:'error',text:'失敗',dialog:modal}});assert.equal(panel.dataset.state,'error');
handlers['local_narration.consult_status']({detail:{state:'running',text:'相談中',dialog:modal}});
handlers['local_narration.consult_status']({detail:{state:'cancel',text:'相談を閉じました',dialog:modal}});assert.equal(panel.parentElement,body);
console.log('PASS consultation background status, elapsed time, completion/error/dismissal, unrelated execution isolation');
